import 'dart:math';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:shoesly/common/http/response.dart';
import 'package:shoesly/common/util/log.dart';
import 'package:shoesly/feature/product/model/category_model.dart';

class CategoryRepository {
  final CollectionReference productCollection =
      FirebaseFirestore.instance.collection("category");

  // List<String> brands = [
  //   "Adidas",
  //   "Asics",
  //   "Reebok",
  //   "Puma",
  //   "Vans",
  //   "New Balance",
  //   "Jordans",
  //   "Fila",
  //   "Nike",
  //   "Under Armour",
  //   "Yeezy",
  //   "Converse",
  //   "Lacoste",
  //   "Gucci",
  //   "Gibson",
  //   "Hush Puppies",
  //   "Balenciaga",
  //   "Prada",
  //   "Vans",
  //   "Hermes",
  // ];
  // List<double> ratings = [
  //   0.0,
  //   0.5,
  //   1.0,
  //   1.5,
  //   2.0,
  //   2.5,
  //   3.0,
  //   3.5,
  //   4.0,
  //   4.5,
  //   5.0
  // ];
  // List<double> prices = [
  //   100.0,
  //   150.0,
  //   200.0,
  //   250.0,
  //   300.0,
  //   350.0,
  //   400.0,
  //   450.0,
  //   500.0
  // ];
  // List<String> shoeTitles = [
  //   "Classic Leather Sneakers",
  //   "Running Shoes Pro",
  //   "High-Top Basketball Shoes",
  //   "Trail Running Shoes",
  //   "Comfort Walking Shoes",
  //   "Elegant Dress Shoes",
  //   "Lightweight Tennis Shoes",
  //   "Breathable Running Shoes",
  //   "Waterproof Hiking Boots",
  //   "Slip-On Casual Shoes",
  //   "Stylish Loafers",
  //   "Chunky Sole Sneakers",
  //   "Classic Skate Shoes",
  //   "Rugged Work Boots",
  //   "Leather Chelsea Boots",
  //   "Suede Desert Boots",
  //   "Minimalist Running Shoes",
  //   "Orthopedic Walking Shoes",
  //   "Premium Running Shoes",
  //   "Retro High-Top Sneakers",
  //   "Mesh Training Shoes",
  //   "Eco-Friendly Running Shoes",
  //   "Luxurious Leather Oxfords",
  //   "Vintage Suede Sneakers",
  //   "All-Terrain Running Shoes",
  //   "Comfort Gel Walking Shoes",
  //   "Breathable Mesh Sneakers",
  //   "High-Performance Running Shoes",
  //   "Lightweight Slip-On Sneakers",
  //   "Elegant Leather Loafers",
  //   "Durable Hiking Shoes",
  //   "Soft Leather Moccasins",
  //   "Athletic Training Shoes",
  //   "Cushioned Running Shoes",
  //   "Water-Resistant Trail Shoes",
  //   "Fashionable Platform Sneakers",
  //   "Leather Monk Strap Shoes",
  //   "Versatile Cross-Training Shoes",
  //   "Ultra-Light Running Shoes",
  //   "Sporty Slip-On Shoes",
  //   "Classic Boat Shoes",
  //   "Chukka Boots",
  //   "Premium Leather Boots",
  //   "Flexible Running Shoes",
  //   "Breathable Walking Shoes",
  //   "All-Purpose Athletic Shoes",
  //   "Performance Basketball Shoes",
  //   "Stylish Ankle Boots",
  //   "Soft Padded Running Shoes",
  //   "Vintage Leather Sneakers",
  //   "Sporty Running Shoes",
  //   "Lightweight Running Sneakers",
  //   "Premium Walking Shoes",
  //   "Comfortable Dress Shoes",
  //   "Durable Work Boots",
  //   "High-Performance Athletic Shoes",
  //   "Breathable Trail Shoes",
  //   "Fashionable Casual Shoes",
  //   "Classic Oxford Shoes",
  //   "Elegant Suede Loafers",
  //   "Lightweight Hiking Boots",
  //   "Performance Training Shoes",
  //   "Stylish Running Shoes",
  //   "Waterproof Walking Shoes",
  //   "Breathable Mesh Running Shoes",
  //   "Luxurious Dress Boots",
  //   "Retro Running Shoes",
  //   "High-Performance Tennis Shoes",
  //   "Comfort Gel Running Shoes",
  //   "Eco-Friendly Walking Shoes",
  //   "All-Terrain Hiking Boots",
  //   "Lightweight Athletic Shoes",
  //   "Premium Leather Loafers",
  //   "Fashionable Sneakers",
  //   "Breathable Training Shoes",
  //   "Comfort Gel Sneakers",
  //   "Vintage Athletic Shoes",
  //   "Durable Running Shoes",
  //   "All-Weather Hiking Boots",
  //   "Lightweight Dress Shoes",
  //   "Orthopedic Running Shoes",
  //   "Luxurious Casual Shoes",
  //   "Flexible Walking Shoes",
  //   "Retro Sneakers",
  //   "High-Performance Training Shoes",
  //   "Premium Running Sneakers",
  //   "Fashionable Athletic Shoes",
  //   "Comfort Gel Walking Sneakers",
  //   "Breathable Walking Sneakers",
  //   "Waterproof Trail Running Shoes",
  //   "Elegant Leather Boots",
  //   "Durable Work Shoes",
  //   "Stylish Dress Shoes",
  //   "Lightweight Walking Shoes",
  //   "High-Performance Sneakers",
  //   "Fashionable Training Shoes",
  //   "Breathable Athletic Shoes",
  //   "Comfort Gel Running Sneakers",
  //   "Luxurious Hiking Boots",
  //   "Premium Trail Shoes",
  //   "Retro Running Sneakers",
  //   "Waterproof Walking Sneakers",
  //   "Flexible Athletic Shoes",
  //   "Breathable Casual Shoes",
  //   "High-Performance Hiking Boots",
  //   "Fashionable Dress Shoes",
  //   "Lightweight Training Shoes",
  //   "Durable Running Sneakers",
  //   "Orthopedic Walking Sneakers",
  //   "Luxurious Dress Shoes",
  //   "Comfort Gel Athletic Shoes",
  //   "Breathable Training Sneakers",
  //   "Stylish Casual Sneakers",
  //   "High-Performance Walking Shoes",
  //   "Waterproof Running Shoes",
  //   "Elegant Dress Boots",
  //   "Durable Hiking Sneakers",
  //   "Fashionable Walking Shoes",
  //   "Lightweight Running Shoes",
  //   "Breathable Athletic Sneakers",
  //   "Comfort Gel Trail Shoes",
  //   "Premium Training Shoes",
  //   "Retro Walking Shoes",
  //   "High-Performance Dress Shoes",
  //   "Waterproof Hiking Shoes",
  //   "Flexible Training Shoes",
  //   "Luxurious Casual Sneakers",
  //   "Breathable Running Sneakers",
  //   "Durable Trail Running Shoes",
  //   "Orthopedic Athletic Shoes",
  //   "High-Performance Casual Shoes",
  //   "Comfort Gel Dress Shoes",
  //   "Premium Running Shoes",
  //   "Fashionable Hiking Boots",
  //   "Breathable Walking Shoes",
  //   "Luxurious Athletic Shoes",
  //   "Retro Casual Shoes",
  //   "High-Performance Running Sneakers",
  //   "Waterproof Training Shoes",
  //   "Flexible Walking Sneakers",
  //   "Durable Dress Shoes",
  //   "Orthopedic Hiking Shoes",
  //   "Fashionable Running Shoes",
  //   "Comfort Gel Training Shoes",
  //   "Luxurious Walking Shoes",
  //   "Breathable Trail Shoes",
  //   "High-Performance Casual Sneakers",
  //   "Waterproof Athletic Shoes",
  //   "Flexible Running Shoes",
  //   "Retro Walking Sneakers",
  //   "Premium Casual Shoes",
  //   "Comfort Gel Hiking Shoes",
  //   "Durable Athletic Sneakers",
  //   "Orthopedic Walking Shoes",
  //   "Breathable Dress Shoes",
  //   "Luxurious Running Shoes",
  //   "High-Performance Hiking Shoes",
  //   "Fashionable Trail Shoes",
  //   "Comfort Gel Walking Shoes",
  //   "Flexible Training Sneakers",
  //   "Durable Running Shoes",
  //   "Breathable Casual Shoes",
  //   "Orthopedic Athletic Sneakers",
  //   "Luxurious Dress Shoes",
  //   "High-Performance Walking Shoes",
  //   "Fashionable Training Shoes",
  //   "Comfort Gel Athletic Sneakers",
  //   "Premium Running Shoes",
  //   "Flexible Casual Sneakers",
  //   "Durable Hiking Shoes",
  //   "Breathable Walking Sneakers",
  //   "Orthopedic Trail Shoes",
  //   "Luxurious Running Sneakers",
  //   "High-Performance Casual Shoes",
  //   "Comfort Gel Training Shoes",
  //   "Fashionable Athletic Shoes",
  //   "Flexible Walking Shoes",
  //   "Durable Dress Sneakers",
  //   "Breathable Running Shoes",
  //   "Orthopedic Hiking Boots",
  //   "Luxurious Trail Shoes",
  //   "High-Performance Walking Sneakers",
  //   "Fashionable Casual Sneakers",
  //   "Comfort Gel Running Shoes",
  //   "Flexible Athletic Shoes",
  //   "Durable Training Sneakers",
  //   "Breathable Casual Shoes",
  //   "Orthopedic Running Shoes",
  //   "Luxurious Hiking Shoes",
  //   "High-Performance Training Shoes",
  //   "Fashionable Walking Sneakers",
  //   "Comfort Gel Dress Shoes",
  //   "Premium Athletic Sneakers",
  //   "Flexible Running Sneakers",
  //   "Durable Hiking Boots",
  //   "Breathable Walking Shoes",
  //   "Orthopedic Running Sneakers",
  //   "Luxurious Training Shoes",
  //   "High-Performance Hiking Boots",
  //   "Fashionable Casual Boots",
  //   "Comfort Gel Athletic Boots",
  //   "Premium Walking Sneakers",
  //   "Flexible Hiking Boots",
  //   "Durable Training Boots",
  //   "Breathable Running Boots",
  //   "Orthopedic Running Sneakers",
  //   "Luxurious Hiking Boots",
  //   "High-Performance Training Boots",
  // ];

  // //gender list
  // List<String> gender = [
  //   "Men",
  //   "Women",
  //   "Unisex",
  //   "Kids",
  //   "All",
  // ];

  // List<String> color = [
  //   "FFFFFF",
  //   "234FFF",
  //   "FF0000",
  //   "0000FF",
  //   "00FF00",
  //   "FF00FF",
  //   "FFFF00",
  //   "00FFFF",
  //   "000000",
  //   "808080",
  //   "800000",
  //   "808000",
  //   "800080",
  //   "008000",
  //   "008080",
  //   "000080",
  //   "FFA500",
  //   "FFD700",
  //   "808000",
  //   "800080",
  //   "008000",
  //   "008080",
  //   "000080",
  // ];

  // addCategory() async {
  //   // Create a mocked Firebase Database instanc
  //   Random random = Random();

  //   for (int i = 0; i < shoeTitles.length; i++) {
  //     final res = await FirebaseFirestore.instance.collection("products").add({
  //       "id": i,
  //       "category_id": random.nextInt(brands.length),
  //       "name": shoeTitles[i],
  //       "rating": ratings[random.nextInt(ratings.length)],
  //       "size": [38, 39, 40, 41, 42, 43, 44],
  //       "description": "This is a description",
  //       "price": prices[random.nextInt(prices.length)],
  //       "color": color[random.nextInt(color.length)],
  //       "gender": gender[random.nextInt(gender.length)],
  //     });
  //   }
  // }

  
  
  List<CategoryModel> categories = [];
  //set categories
  void setCategories(List<CategoryModel> _categories) =>
      categories = _categories;

  //get categories
  List<CategoryModel> get getCategories => categories;

  Future<DataResponse<List<CategoryModel>>> fetchCategory() async {
    try {
      final res = await productCollection.get();

      final _data = res.docs
          .map((doc) =>
              CategoryModel.fromMap(doc.id, doc.data() as Map<String, dynamic>))
          .toList();
      setCategories(_data);
      return DataResponse.success(_data);
    } catch (e, s) {
      Log.e(e);
      Log.d(s);
      return DataResponse.error(e.toString());
    }
  }
}
